# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (Every Day)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Metrics
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: xero-lib
          template: classic
          base: header
          base_hireable: yes
          base_indepth: yes
          config_order: base.header, isocalendar. languages, notable
          config_timezone: America/Chicago
          config_twemoji: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, vue, scala, c, c++, python, ejs
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 2
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_notable: yes
          plugin_discussions: yes
          # plugin_achievements: yes
          # plugin_achievements_display: detailed
          # plugin_achievements_secrets: yes
          # plugin_achievements_threshold: C
          # plugin_activity: yes
          # plugin_activity_days: 14
          # plugin_activity_filter: all
          # plugin_activity_limit: 5
          # plugin_activity_load: 300
          # plugin_activity_visibility: all
          # plugin_followup: yes
          # plugin_followup_archived: yes
          # plugin_followup_sections: repositories
          # plugin_habits: yes
          # plugin_habits_charts_type: classic
          # plugin_habits_days: 14
          # plugin_habits_facts: yes
          # plugin_habits_from: 200
          # plugin_habits_languages_limit: 8
          # plugin_habits_languages_threshold: 0%
          # plugin_isocalendar: yes
          # plugin_isocalendar_duration: full-year
          # plugin_languages: yes
          # plugin_languages_analysis_timeout: 15
          # plugin_languages_analysis_timeout_repositories: 7.5
          # plugin_languages_categories: markup, programming
          # plugin_languages_colors: github
          # plugin_languages_limit: 8
          # plugin_languages_recent_categories: markup, programming
          # plugin_languages_recent_days: 14
          # plugin_languages_recent_load: 300
          # plugin_languages_sections: most-used
          # plugin_languages_threshold: 0%
          # plugin_lines: yes
          # plugin_lines_history_limit: 10
          # plugin_lines_repositories_limit: 1000000
          # plugin_lines_sections: base
          # plugin_people: yes
          # plugin_people_limit: 24
          # plugin_people_size: 28
          # plugin_people_types: followers, following
          # plugin_repositories: yes
          # plugin_repositories_order: featured, pinned, starred, random
          # plugin_repositories_pinned: 6
      - name: Achievements
        uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_fortune: yes
          plugin_achievements_threshold: C
